name: Deploy_To_PROD_APIM_On_Push

# Runs when a Release is published from GitHub UI
on:
  release:
    types: [published]

jobs:
  deploy-apim-prod:
    runs-on: ubuntu-latest

    env:
      Environment: prod
      UrlEnvPrefix: ""
      SubscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      resourceGroup: rg-apim-PROD
      AZURE_CREDENTIALS: ${{ secrets.PROD_AZURE_CREDENTIALS }}
      ApimServiceName: apim-iati-PROD
      ApimGatewayHostname: api.iatistandard.org
      ApimDevPortalHostname: developer.iatistandard.org
      ApimSKU: Basic
      ApimCapacity: 2 # Basic - max 2
      repoUrl: https://raw.githubusercontent.com/iati/apim-iati-gateway
      repoBranch: ${GITHUB_REF##*/}
      repoApimPath: service
      RedisConnectionString: ${{ secrets.PROD_REDIS_CONNECTION_STRING }}
      ApplicationInsightsInstanceName: appi-apim
      SolrBaseUrl: ${{ secrets.PROD_SOLR_BASE_URL }}
      Branch: main

    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v2

      - name: "Login to Azure"
        uses: azure/login@v1.3.0
        with:
          creds: ${{ env.AZURE_CREDENTIALS }}

      # ARM deployment tasks
      - name: Deploy APIM Service and APIs
        working-directory: ./service
        env:
          LinkedTemplatesBaseUrl: ${{ env.repoUrl }}/${{ env.repoBranch }}/${{ env.repoApimPath }}
          PolicyXMLBaseUrl: ${{ env.repoUrl }}/${{ env.repoBranch }}/${{ env.repoApimPath }}/policies
          deploymentName: --name GH_PROD_deployment_apim
          rg: --resource-group ${{ env.resourceGroup }}
          apiNamePrefix: apim-iati-dev
        run: |
          az deployment group create ${{env.deploymentName}} \
            ${{env.rg}} \
            --template-file ./${{env.apiNamePrefix}}-master.template.json \
            --parameters ./${{env.apiNamePrefix}}-parameters.json \
            --parameters ApimServiceName=${{ env.ApimServiceName }} \
            --parameters LinkedTemplatesBaseUrl=${{ env.LinkedTemplatesBaseUrl }} \
            --parameters PolicyXMLBaseUrl=${{ env.PolicyXMLBaseUrl }} \
            --parameters Environment=${{ env.Environment }} \
            --parameters UrlEnvPrefix=${{ env.UrlEnvPrefix }} \
            --parameters SubscriptionId=${{ env.SubscriptionId }} \
            --parameters ApimSKU=${{ env.ApimSKU }} \
            --parameters ApimCapacity=${{ env.ApimCapacity }} \
            --parameters ApimGatewayHostname=${{ env.ApimGatewayHostname }} \
            --parameters ApimDevPortalHostname=${{ env.ApimDevPortalHostname }} \
            --parameters RedisConnectionString=${{ env.RedisConnectionString }} \
            --parameters ApplicationInsightsInstanceName=${{ env.ApplicationInsightsInstanceName }} \
            --parameters SolrBaseUrl=${{ env.SolrBaseUrl }} \
            --parameters Branch=${{ env.Branch }}
