name: Validate_APIM_On_PR_to_Dev

on:
  pull_request:
    branches:
      - develop
    paths:
      - "service/**"
      - ".github/workflows/apim-ci.yml"
      - ".github/workflows/apim-develop.yml"

jobs:
  validate-apim:
    runs-on: ubuntu-latest

    env:
      Environment: dev
      UrlEnvPrefix: dev-
      SubscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      resourceGroup: rg-apim-dev
      AZURE_CREDENTIALS: ${{ secrets.DEV_AZURE_CREDENTIALS }}
      apimServiceName: apim-iati-dev
      ApimGatewayHostname: dev-api.iatistandard.org
      ApimDevPortalHostname: dev-developer.iatistandard.org
      ApimSKU: Developer
      ApimCapacity: 1
      repoUrl: https://raw.githubusercontent.com/iati/apim-iati-gateway
      repoApimPath: service
      RedisConnectionString: ${{ secrets.DEV_REDIS_CONNECTION_STRING }}
      ApplicationInsightsInstanceName: appi-apim
      SolrBaseUrl: ${{ secrets.DEV_SOLR_BASE_URL }}
      Branch: develop

    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v2

      - name: "Login to Azure"
        uses: azure/login@v1.3.0
        with:
          creds: ${{ env.AZURE_CREDENTIALS }}

      # ARM deployment tasks
      - name: Validate APIM ARM Templates with what-if
        working-directory: ./service
        env:
          linkedTemplatesBaseUrl: ${{ env.repoUrl }}/${{ github.HEAD_REF }}/${{ env.repoApimPath }}/
          policyXMLBaseUrl: ${{ env.repoUrl }}/${{ github.HEAD_REF }}/${{ env.repoApimPath }}/policies/
          deploymentName: --name GH_what_if_deployment_apim
          rg: --resource-group ${{ env.resourceGroup }}
          apiNamePrefix: apim-iati-dev
        run: |
          az deployment group what-if ${{env.deploymentName}} \
            ${{env.rg}} \
            --template-file ./${{env.apiNamePrefix}}-master.template.json \
            --parameters ./${{env.apiNamePrefix}}-parameters.json \
            --parameters ./manual-parameters.json \
            --parameters apimServiceName=${{ env.apimServiceName }} \
            --parameters linkedTemplatesBaseUrl=${{ env.linkedTemplatesBaseUrl }} \
            --parameters policyXMLBaseUrl=${{ env.policyXMLBaseUrl }} \
            --parameters Environment=${{ env.Environment }} \
            --parameters UrlEnvPrefix=${{ env.UrlEnvPrefix }} \
            --parameters SubscriptionId=${{ env.SubscriptionId }} \
            --parameters ApimSKU=${{ env.ApimSKU }} \
            --parameters ApimCapacity=${{ env.ApimCapacity }} \
            --parameters ApimGatewayHostname=${{ env.ApimGatewayHostname }} \
            --parameters ApimDevPortalHostname=${{ env.ApimDevPortalHostname }} \
            --parameters RedisConnectionString=${{ env.RedisConnectionString }} \
            --parameters ApplicationInsightsInstanceName=${{ env.ApplicationInsightsInstanceName }} \
            --parameters Branch=${{ env.Branch }} \
            --parameters '{"serviceUrl":{"value":{"apidefinitionsrev1":"","api61e68d73c8e44ca9124dcddbrev1":"${{ env.SolrBaseUrl }}","datastorerev1":"${{ env.SolrBaseUrl }}","datastorerev2":"${{ env.SolrBaseUrl }}","datastorerev3":"${{ env.SolrBaseUrl }}","datastorerev4":"${{ env.SolrBaseUrl }}","iativalidatorv2rev1":"","iativalidatorv2rev2":"","iativalidatorv2rev3":"","validatorservicesprivaterev1":""}}}'
